resilience4j.circuitbreaker.instances.PFEnquiryService_Child.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.PFEnquiryService_Child.slidingWindowSize=10
resilience4j.circuitbreaker.instances.PFEnquiryService_Child.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.PFEnquiryService_Child.failureRateThreshold=50
resilience4j.circuitbreaker.instances.PFEnquiryService_Child.waitDurationInOpenState=10000
resilience4j.circuitbreaker.instances.PFEnquiryService_Child.permittedNumberOfCallsInHalfOpenState=3